<?php

namespace App\Containers\User\DTO;

use App\Abstractions\DTO\DataTransferObject;
use App\Containers\User\Enums\GenderEnum;
use App\Containers\User\Enums\UserRoleEnum;

/**
 *
 */
class UserDto extends DataTransferObject
{
    /**
     * @var string
     */
    public string $name;

    /**
     * @var string
     */
    public string $login;

    /**
     * @var string
     */
    public string $phone;

    /**
     * @var string
     */
    public string $password;

    /**
     * @var string|null
     */
    public ?string $email = null;

    /**
     * @var UserRoleEnum|null
     */
    public ?UserRoleEnum $role = null;

    /**
     * @var GenderEnum|null
     */
    public ?GenderEnum $gender = GenderEnum::UNKNOWN;

    /**
     * @var string|null
     */
    public ?string $source_id = null;


    /**
     * @param array $data
     * @return static
     */
    public static function of(array $data): static
    {
        $data["role"] = isset($data['role'])
            ? UserRoleEnum::tryFrom($data["role"])
            : null;

        try {
            $data['gender'] = isset($data['gender'])
                ? GenderEnum::tryFrom($data['gender'])
                : GenderEnum::UNKNOWN;
        } catch (\Exception $exception) {
            $data["gander"] = GenderEnum::UNKNOWN;
        }

        return parent::of($data); // TODO: Change the autogenerated stub
    }
}
